version: '3'

services: 
  frontend:
    build: ./frontend/
    ports:
      - '3000:1234'
    volumes:
      - './frontend:/frontend/'
    links:
      - api
  api:
    build: ./api/
    ports: 
      - '4000:4000'
    volumes:
      - './api:/api/'
